# Generated by Django 2.2.12 on 2022-02-02 23:20

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('FivePThreeSTwoR_Info', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gray_votes',
        ),
        migrations.AddField(
            model_name='group',
            name='purple_votes',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='opinion',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Purple'], [0, 'Indifferent']], null=True, verbose_name='Which project do you prefer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Purple']], null=True, verbose_name='Which project would you like to get implemented?'),
        ),
    ]
