# Generated by Django 2.2.12 on 2021-11-17 11:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('FivePlayersFiveSignals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opinion',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Gray'], [0, 'Indifferent']], null=True, verbose_name='Which project do you prefer?'),
        ),
    ]
