# Generated by Django 2.2.12 on 2021-11-17 11:36

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('FivePlayersFiveSignals', '0002_auto_20211117_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opinion_iteration5',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
    ]
