# Generated by Django 2.2.12 on 2021-11-17 12:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('FivePlayersFiveSignals', '0003_player_opinion_iteration5'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_votes',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
