# Generated by Django 2.2.12 on 2022-11-29 19:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('FivePlayersFiveSignals', '0004_group_group_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='opinion',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Purple'], [0, 'Indifferent']], null=True, verbose_name='Which project do you prefer?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Purple']], null=True, verbose_name='Which project would you like to get implemented?'),
        ),
    ]
