# Generated by Django 2.2.12 on 2021-08-23 20:27

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='correct_guess',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_decision1',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_decision2',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_decision3',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_information1',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_information2',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_information3',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='gray_votes',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='group_guess',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opinions_result1',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opinions_result2',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opinions_result3',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='public_evidence',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='state_of_world',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='str_group_guess',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='str_public_evidence',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='MyNumber',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='disclose',
            field=otree.db.models.IntegerField(blank=True, choices=[[1, 'Yes'], [0, 'No']], default=0, null=True, verbose_name='Would you like to disclose your private evidence?'),
        ),
        migrations.AddField(
            model_name='player',
            name='earnings',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='opinion',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Gray'], [0, 'None']], null=True, verbose_name='Which project do you prefer?'),
        ),
        migrations.AddField(
            model_name='player',
            name='private_evidence',
            field=otree.db.models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='publicized_evidence',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='str_private_evidence',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='type',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='vote',
            field=otree.db.models.IntegerField(choices=[[0, 'Orange'], [1, 'Gray']], null=True, verbose_name='Which project would you like to get implemented?'),
        ),
    ]
