# Generated by Django 2.2.12 on 2021-09-07 14:07

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0002_auto_20210823_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='final_earnings',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='final_profit',
            field=otree.db.models.CurrencyField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='paying_round',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
