# Generated by Django 2.2.12 on 2021-09-13 02:31

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0004_player_iteration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='iteration',
            field=otree.db.models.IntegerField(default=2, null=True),
        ),
    ]
