# Generated by Django 2.2.12 on 2021-09-13 03:04

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0005_auto_20210912_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='iteration',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
