# Generated by Django 2.2.12 on 2021-09-13 12:10

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0006_auto_20210912_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opinion_iteration1',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
    ]
