# Generated by Django 2.2.12 on 2021-10-31 20:43

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0008_player_opinion_iteration2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='vote',
            field=otree.db.models.IntegerField(choices=[[1, 'Orange'], [-1, 'Gray']], null=True, verbose_name='Which project would you like to get implemented?'),
        ),
    ]
