# Generated by Django 2.2.12 on 2021-10-31 23:02

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('No_info_treatment', '0010_auto_20211031_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opinion_iteration3',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='opinion_iteration4',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
    ]
