# Generated by Django 2.2.12 on 2021-07-26 14:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='publicized_evidence',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
