# Generated by Django 2.2.12 on 2021-09-10 21:08

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0002_auto_20210907_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='iteration',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
