# Generated by Django 2.2.12 on 2021-09-13 03:05

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0004_auto_20210912_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='iteration',
            field=otree.db.models.IntegerField(default=0, null=True),
        ),
    ]
