# Generated by Django 2.2.12 on 2021-09-13 13:24

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0005_auto_20210912_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='opinion_iteration1',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='opinion_iteration2',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
    ]
