# Generated by Django 2.2.12 on 2021-10-31 22:46

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0007_auto_20211031_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='disclosure_decision4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_decision5',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_information4',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='disclosure_information5',
            field=otree.db.models.StringField(default='None', max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opinions_result4',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='opinions_result5',
            field=otree.db.models.StringField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='opinion_iteration3',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='opinion_iteration4',
            field=otree.db.models.IntegerField(default=-2, null=True),
        ),
    ]
