# Generated by Django 2.2.12 on 2021-11-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collective_deliberation_infoTreatment', '0008_auto_20211031_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='disclosure_decision4',
        ),
        migrations.RemoveField(
            model_name='group',
            name='disclosure_decision5',
        ),
        migrations.RemoveField(
            model_name='group',
            name='disclosure_information4',
        ),
        migrations.RemoveField(
            model_name='group',
            name='disclosure_information5',
        ),
        migrations.RemoveField(
            model_name='group',
            name='opinions_result4',
        ),
        migrations.RemoveField(
            model_name='group',
            name='opinions_result5',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opinion_iteration3',
        ),
        migrations.RemoveField(
            model_name='player',
            name='opinion_iteration4',
        ),
    ]
